spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ded_kursach
    username: postgres
    password: passekss
    #password: autism24Au #- password for linux database
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect